// Regenerate catalog-data.js from a pasted course catalog text file.
// Usage: node generate-catalog.mjs "C:\path\to\catalog.txt"
import fs from 'node:fs';

const CATALOG_DAY_MAP = { M: 'Mon', T: 'Tue', W: 'Wed', Th: 'Thu', F: 'Fri', Sa: 'Sat', Su: 'Sun' };

function to24Hour(str) {
  const m = str.match(/(\d{1,2}):(\d{2})\s*([AP]M)/);
  if (!m) return null;
  let h = parseInt(m[1], 10);
  const min = m[2];
  const mer = m[3];
  if (mer === 'AM') { if (h === 12) h = 0; } else if (h !== 12) h += 12;
  return String(h).padStart(2, '0') + ':' + min;
}

function normalizeMeetingTime(startRaw, endRaw) {
  const endMeridiem = endRaw.match(/([AP]M)$/)[1];
  const end = to24Hour(endRaw);
  const hasOwnMeridiem = /[AP]M$/.test(startRaw);
  const start = hasOwnMeridiem ? to24Hour(startRaw) : to24Hour(startRaw + ' ' + endMeridiem);
  return { start, end };
}

function parseCatalogText(text) {
  const lines = text.split(/\r?\n/).map((l) => l.trim());
  const codeRe = /^[A-Z]{2,6}-\d{2,4}-[A-Z0-9]+$/;
  const dayTimeRe = /^((?:M|T|W|Th|F|Sa|Su)(?:,\s*(?:M|T|W|Th|F|Sa|Su))*)\s+(\d{1,2}:\d{2}(?:\s*[AP]M)?)\s*-\s*(\d{1,2}:\d{2}\s*[AP]M)$/;
  const dateRangeRe = /^\d{1,2}\/\d{1,2}\/\d{4}\s*-\s*\d{1,2}\/\d{1,2}\/\d{4}$/;
  const enrollRe = /^\d+\s*\/\s*\d+\s*\/\s*\d+$/;
  const levelRe = /^(Undergraduate|Graduate)$/;
  const statusRe = /^(Open|Waitlisted|Closed|Cancelled)$/i;

  const codeIdxs = [];
  lines.forEach((l, i) => { if (codeRe.test(l)) codeIdxs.push(i); });

  const sections = [];
  for (let k = 0; k < codeIdxs.length; k++) {
    const start = codeIdxs[k];
    const end = k + 1 < codeIdxs.length ? codeIdxs[k + 1] : lines.length;
    const code = lines[start];
    const title = lines[start + 1] || '';
    const chunk = lines.slice(start, end);

    let status = '';
    for (let i = start - 1; i >= Math.max(0, start - 3); i--) {
      if (statusRe.test(lines[i])) { status = lines[i]; break; }
    }

    let level = '';
    for (const l of chunk) { if (levelRe.test(l)) { level = l; break; } }

    const meetings = [];
    let lastConsumedIdx = 1;
    for (let i = 2; i < chunk.length; i++) {
      const m = chunk[i].match(dayTimeRe);
      if (!m) continue;
      const days = m[1].split(',').map((d) => CATALOG_DAY_MAP[d.trim()]).filter(Boolean);
      const { start: startTime, end: endTime } = normalizeMeetingTime(m[2], m[3]);
      let room = '';
      let consumedTo = i;
      if (dateRangeRe.test(chunk[i + 1] || '')) {
        consumedTo = i + 1;
        if (chunk[i + 2]) {
          room = chunk[i + 2].replace(/\s*\([^)]*\)\s*$/, '').trim();
          consumedTo = i + 2;
        }
      }
      if (startTime && endTime) meetings.push({ days, start: startTime, end: endTime, room });
      lastConsumedIdx = Math.max(lastConsumedIdx, consumedTo);
    }

    const enrollIdx = chunk.findIndex((l) => enrollRe.test(l));
    let instructors = [];
    if (enrollIdx > lastConsumedIdx) {
      instructors = chunk.slice(lastConsumedIdx + 1, enrollIdx).filter((l) => l && l !== 'Registered');
    }

    if (meetings.length === 0) continue;

    sections.push({ code, title, status, level, instructors, meetings });
  }
  return sections;
}

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: node generate-catalog.mjs "path/to/catalog.txt"');
  process.exit(1);
}

const text = fs.readFileSync(inputPath, 'utf8');
const sections = parseCatalogText(text);
const out = `// Auto-generated by generate-catalog.mjs — do not hand-edit.\nconst CATALOG_DATA = ${JSON.stringify(sections)};\n`;
fs.writeFileSync(new URL('./catalog-data.js', import.meta.url), out);
console.log(`Wrote catalog-data.js with ${sections.length} sections.`);
